import { NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { orderedCategories } = body;

    if (!orderedCategories || !Array.isArray(orderedCategories)) {
      return NextResponse.json({ error: 'Invalid data format.' }, { status: 400 });
    }

    // We use a transaction so it either all succeeds or all fails safely
    await prisma.$transaction(async (tx) => {
      // 1. Clear out the old order
      await tx.category.deleteMany({});
      
      // 2. Insert the new ones with their updated names and sortOrders
      if (orderedCategories.length > 0) {
        await tx.category.createMany({
          data: orderedCategories.map((cat: any) => ({
            id: cat.id, // Using the ID generated by the frontend
            name: cat.name,
            sortOrder: cat.sortOrder,
          })),
        });
      }
    });

    return NextResponse.json({ message: 'Categories saved successfully!' }, { status: 200 });
    
  } catch (error) {
    console.error('Error saving categories:', error);
    return NextResponse.json({ error: 'Failed to save categories.' }, { status: 500 });
  }
}